const mongoose = require('mongoose');
const Company = require('./models/Company');
require('dotenv').config();

const companies = [
  {
    name: 'Eco-Friendly Packaging Manufacturer',
    tagline: 'Sustainable packaging solutions for global brands',
    industry: 'Manufacturing',
    badge: 'PREMIUM',
    transactionType: 'Investment Opportunity',
    investment: '$1.5M - $2.0M',
    revenue: '$500k /yr',
    employees: 25,
    location: 'Dubai, UAE',
    country: 'UAE',
    established: 2018,
    about: 'A leading eco-friendly packaging manufacturer based in Dubai, specializing in biodegradable and recyclable packaging solutions for FMCG, e-commerce, and retail sectors. The company holds multiple certifications for sustainable manufacturing.',
    description: 'Founded in 2018, this company has grown to serve over 200 clients across the GCC region. With state-of-the-art machinery and a dedicated R&D team, they are well-positioned for rapid expansion into European markets.',
    image: 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=400&q=80',
    tags: ['Sustainable', 'B2B', 'Export Ready'],
    featured: true,
    rating: 4.7,
    views: 1240,
  },
  {
    name: 'SaaS Enterprise Solutions',
    tagline: 'High-growth B2B SaaS with recurring revenue',
    industry: 'Technology',
    badge: 'NEW LISTING',
    transactionType: 'Business for Sale',
    budget: '$4.2M',
    revenue: '$1.2M /yr',
    employees: 18,
    location: 'Singapore',
    country: 'Singapore',
    established: 2020,
    about: 'A high-growth SaaS platform providing enterprise resource planning and analytics tools to mid-sized companies across Southeast Asia. 90% of revenue is recurring via annual subscriptions.',
    description: 'The company offers a cloud-native ERP solution with integrations to major accounting, HR, and CRM platforms. It currently serves 85 enterprise clients and has a net revenue retention of 118%.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80',
    tags: ['SaaS', 'B2B', 'ARR', 'Cloud'],
    featured: true,
    rating: 4.9,
    views: 2890,
  },
  {
    name: 'Boutique Hotel Group',
    tagline: '4 prime locations with strong occupancy rates',
    industry: 'Hospitality',
    badge: 'VERIFIED',
    transactionType: 'Business for Sale',
    askingPrice: '$12.5M',
    revenue: '$3.8M /yr',
    ebitda: '15%',
    employees: 120,
    location: 'London, UK',
    country: 'UK',
    established: 2010,
    about: 'A well-established boutique hotel group operating four properties in prime London locations. Known for their design-led interiors and personalized guest experience, they maintain an average occupancy rate of 87%.',
    description: 'The group owns the freehold on two properties and holds long-term leases on two others. All hotels are rated 4-star or above on major booking platforms. The business comes with an experienced management team in place.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
    tags: ['Hotels', 'Real Estate', 'Lifestyle', 'B2C'],
    featured: false,
    rating: 4.5,
    views: 980,
  },
  {
    name: 'Diagnostic Center Network',
    tagline: 'Seeking strategic investor for rapid expansion',
    industry: 'Healthcare',
    badge: 'URGENT SALE',
    transactionType: 'Investment Opportunity',
    investment: '$800k',
    revenue: '$200k /yr',
    assets: '$1.2M',
    employees: 35,
    location: 'Mumbai, India',
    country: 'India',
    established: 2015,
    about: 'A network of diagnostic centers offering advanced imaging, pathology, and preventive health checkup packages across Mumbai. The centers are equipped with MRI, CT, and digital X-ray facilities.',
    description: 'The business has seen 45% revenue growth over the last 3 years. With a new investor, the plan is to expand to 8 additional cities across Maharashtra within 18 months. All regulatory approvals are in place.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400&q=80',
    tags: ['Healthcare', 'Diagnostics', 'Expansion'],
    featured: false,
    rating: 4.2,
    views: 650,
  },
  {
    name: 'GreenWave Solar Energy',
    tagline: 'Utility-scale solar projects across MENA region',
    industry: 'Energy',
    badge: 'FEATURED',
    transactionType: 'Investment Opportunity',
    investment: '$8M - $15M',
    revenue: '$2.4M /yr',
    employees: 42,
    location: 'Riyadh, Saudi Arabia',
    country: 'Saudi Arabia',
    established: 2017,
    about: 'A renewable energy company specializing in the design, development, and operation of utility-scale solar photovoltaic projects across the MENA region. The company has 3 operational plants with a combined capacity of 120 MW.',
    description: 'GreenWave Solar has secured power purchase agreements (PPAs) with government utilities in 3 countries. The pipeline includes 500 MW of projects under development. Seeking a strategic partner for co-development and financing.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&q=80',
    tags: ['Solar', 'Renewable', 'ESG', 'PPA'],
    featured: true,
    rating: 4.8,
    views: 3100,
  },
  {
    name: 'AutoTech Precision Parts',
    tagline: 'ISO-certified auto components manufacturer',
    industry: 'Manufacturing',
    badge: 'VERIFIED',
    transactionType: 'Business for Sale',
    askingPrice: '$6.5M',
    revenue: '$4.1M /yr',
    ebitda: '22%',
    employees: 180,
    location: 'Stuttgart, Germany',
    country: 'Germany',
    established: 2005,
    about: 'A precision auto-parts manufacturer supplying Tier 1 and Tier 2 automotive OEMs across Europe. Specializes in CNC-machined components, stamped metal parts, and plastic injection-molded assemblies.',
    description: 'The company holds ISO 9001 and IATF 16949 certifications. 80% of revenue comes from long-term supply contracts with 4 major automotive groups. Excellent machinery and a skilled workforce of 180 employees.',
    image: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=400&q=80',
    tags: ['Automotive', 'B2B', 'Manufacturing', 'Export'],
    featured: false,
    rating: 4.6,
    views: 1780,
  },
  {
    name: 'HealthFirst Pharmacy Chain',
    tagline: '12-store retail pharmacy with strong community presence',
    industry: 'Healthcare',
    badge: 'PREMIUM',
    transactionType: 'Business for Sale',
    askingPrice: '$9.2M',
    revenue: '$6.8M /yr',
    employees: 95,
    location: 'Toronto, Canada',
    country: 'Canada',
    established: 2008,
    about: 'A well-established chain of 12 retail pharmacies across the Greater Toronto Area offering prescription services, OTC products, and private-label wellness products.',
    description: 'The chain has strong community relationships with an average of 15 years in each neighborhood. The business includes a loyalty program with 45,000 active members. All locations are profitable with leases secured through 2030.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80',
    tags: ['Retail', 'Healthcare', 'B2C', 'Franchise Ready'],
    featured: false,
    rating: 4.4,
    views: 890,
  },
  {
    name: 'CloudNative DevOps Platform',
    tagline: 'AI-powered CI/CD and infrastructure automation',
    industry: 'Technology',
    badge: 'NEW LISTING',
    transactionType: 'Investment Opportunity',
    investment: '$3M',
    revenue: '$800k /yr',
    employees: 12,
    location: 'Austin, TX, USA',
    country: 'USA',
    established: 2022,
    about: 'An early-stage DevOps SaaS startup offering AI-powered deployment pipelines, infrastructure-as-code templates, and real-time monitoring dashboards for cloud-native teams.',
    description: 'The platform integrates with AWS, Azure, GCP, and Kubernetes. Currently serving 60 paying customers with an NPS of 72. Seeking Series A funding to scale GTM and expand engineering team.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80',
    tags: ['AI', 'DevOps', 'SaaS', 'Series A'],
    featured: true,
    rating: 4.8,
    views: 4200,
  },
  {
    name: 'Seaside Resort & Spa',
    tagline: 'Premium beachfront resort with luxury amenities',
    industry: 'Hospitality',
    badge: 'PREMIUM',
    transactionType: 'Business for Sale',
    askingPrice: '$28M',
    revenue: '$7.5M /yr',
    ebitda: '28%',
    employees: 240,
    location: 'Bali, Indonesia',
    country: 'Indonesia',
    established: 2012,
    about: 'A 5-star beachfront resort in Bali featuring 85 villas, 3 restaurants, a world-class spa, and private beach access. The resort is consistently ranked in the top 10 luxury resorts in Southeast Asia.',
    description: 'The resort operates at 82% average occupancy and serves international clientele through partnerships with leading luxury travel agencies. The business includes the land title and all FF&E.',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
    tags: ['Luxury', 'Resort', 'Real Estate', 'Tourism'],
    featured: false,
    rating: 4.9,
    views: 5600,
  },
  {
    name: 'FinTech Payment Gateway',
    tagline: 'White-label payment solutions for African markets',
    industry: 'Finance',
    badge: 'VERIFIED',
    transactionType: 'Investment Opportunity',
    investment: '$2M',
    revenue: '$1.5M /yr',
    employees: 28,
    location: 'Lagos, Nigeria',
    country: 'Nigeria',
    established: 2019,
    about: 'A licensed payment gateway and digital wallet provider serving merchants and consumers across West Africa. Processes over $50M in transactions per month across 6 countries.',
    description: 'The company holds payment service licenses in Nigeria, Ghana, and Senegal. Offers mobile money, card processing, and BNPL services. Revenue grew 120% YoY. Seeking growth capital to expand into East Africa.',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&q=80',
    tags: ['FinTech', 'Payments', 'Africa', 'Licensed'],
    featured: false,
    rating: 4.5,
    views: 2340,
  },
  {
    name: 'Organic Food & Beverage Brand',
    tagline: 'D2C organic health foods with 50k+ subscribers',
    industry: 'Retail',
    badge: 'PREMIUM',
    transactionType: 'Business for Sale',
    budget: '$5M',
    revenue: '$3.2M /yr',
    employees: 38,
    location: 'Melbourne, Australia',
    country: 'Australia',
    established: 2016,
    about: 'A premium organic food and beverage brand with a strong D2C subscription model and retail presence in 200+ stores across Australia and New Zealand.',
    description: 'The brand has 50,000 active subscribers and a 68% retention rate. Product line includes cold-pressed juices, plant-based snacks, and organic superfoods. Strong social media presence with 320k followers across platforms.',
    image: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=400&q=80',
    tags: ['Organic', 'D2C', 'FMCG', 'Subscription'],
    featured: false,
    rating: 4.7,
    views: 1560,
  },
  {
    name: 'WindPower Infrastructure Co.',
    tagline: 'Onshore wind assets in prime European locations',
    industry: 'Energy',
    badge: 'VERIFIED',
    transactionType: 'Investment Opportunity',
    investment: '$20M+',
    revenue: '$4.2M /yr',
    assets: '$45M',
    employees: 55,
    location: 'Copenhagen, Denmark',
    country: 'Denmark',
    established: 2011,
    about: 'A wind energy infrastructure company with operational wind farms across Denmark, Germany, and Poland. Total installed capacity of 280 MW with long-term grid connection agreements.',
    description: 'The portfolio includes 8 operational wind farms with remaining useful life of 18-25 years. Revenue is secured through government feed-in tariffs and direct PPAs with industrial buyers. Seeking co-investment partners.',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&q=80',
    tags: ['Wind', 'Renewable', 'Infrastructure', 'ESG'],
    featured: true,
    rating: 4.6,
    views: 2100,
  },
];

async function seed() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/companylist';
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    await Company.deleteMany({});
    console.log('🗑️  Cleared existing companies');

    const inserted = await Company.insertMany(companies);
    console.log(`✅ Seeded ${inserted.length} companies successfully`);

    mongoose.disconnect();
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
